### ISSUE TITLE
Can't select text in the Meteor templates

### ISSUE THREAD

**Issue by dandv** [webix-hub/webix-meteor-example#2]
Can't select text in any of the two Meteor template accordions.

**Comment by rpapostolis** [comment]
same here.

**Comment by mkozhukh** [comment]
Fixed. 
https://github.com/webix-hub/webix-meteor-example/blob/master/public/webix-meteor.js#L153

Webix UI disables text selection in complex widgets by default so it will not interfere with drag-n-drop and other actions. This is actually an issue which we can fix in one of the next Webix update ( to allow text selection in all widgets by default and block it only during drag-n-drop and similar actions )
