### ISSUE TITLE
Show scrollbar when content is cut off

### ISSUE THREAD

**Issue by ghost** [webix-hub/webix-meteor-example#3]
Can you show how to display a scrollbar in the "Meteor Data Binding" section (Fullscreen example) when the window is too small to show the whole content.

I struggle with this issue and couldn't find a solution yet.

**Comment by mkozhukh** [comment]
Overflow style need to be added to the "reactive"view.  
You can check the updated samples

**Comment by ghost** [comment]
Thanks.
